steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/instapaper-fetcher', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/instapaper-fetcher']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'instapaper-fetcher'
      - '--image'
      - 'gcr.io/$PROJECT_ID/instapaper-fetcher'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '1000'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'INSTAPAPER_CONSUMER_KEY=$_INSTAPAPER_CONSUMER_KEY,INSTAPAPER_CONSUMER_SECRET=$_INSTAPAPER_CONSUMER_SECRET,INSTAPAPER_ACCESS_TOKEN=$_INSTAPAPER_ACCESS_TOKEN,INSTAPAPER_ACCESS_TOKEN_SECRET=$_INSTAPAPER_ACCESS_TOKEN_SECRET,STORAGE_BUCKET_NAME=$_STORAGE_BUCKET_NAME,GCP_PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/instapaper-fetcher'